import '../../shared/models/app_enums.dart';
import '../../shared/models/track_seed_catalog.dart';

class SeedService {
  const SeedService();

  TrackSeedBundle catalog() {
    return TrackSeedBundle(
      tracks: const [
        TrackSeed(
          id: 'track-data-engineer',
          name: 'Data Engineer',
          description:
              'Pipelines, modelagem analitica, cloud data stack e governanca.',
          iconKey: 'database',
          colorHex: '#005F73',
          roadmapSummary:
              'Fundamentos de SQL, ETL, orquestracao, modelagem analitica e observabilidade.',
          skills: [
            SkillSeed(
              id: 'skill-de-sql',
              name: 'SQL Analitico',
              description: 'Consultas, CTEs, joins, tuning e modelagem.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-de-python',
              name: 'Python para Dados',
              description: 'ETL, APIs, testes e automacoes.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-de-orchestration',
              name: 'Orquestracao',
              description: 'DAGs, jobs agendados e reprocessamento.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-de-cloud',
              name: 'Cloud Data',
              description: 'Storage, warehouse, IAM e custos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-de-sql',
              title: 'SQL Profissional',
              summary: 'Domine SQL para engenharia e analytics.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-python-etl',
              title: 'ETL com Python',
              summary: 'Extracao, transformacao, testes e observabilidade.',
              estimatedHours: 22,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-airflow',
              title: 'Orquestracao de Pipelines',
              summary: 'Airflow, retries, SLA e deploy.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-warehouse',
              title: 'Data Warehouse e Modelagem',
              summary: 'Star schema, particionamento e governanca.',
              estimatedHours: 20,
              sortOrder: 4,
              isCore: true,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-python',
          name: 'Backend Python',
          description:
              'APIs robustas, arquitetura, testes, filas e observabilidade.',
          iconKey: 'server',
          colorHex: '#2EC5FF',
          roadmapSummary:
              'HTTP, FastAPI ou Django, bancos relacionais, filas, cache e deploy.',
          skills: [
            SkillSeed(
              id: 'skill-bpy-python',
              name: 'Python',
              description: 'Sintaxe, tipagem, testes e clean code.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bpy-api',
              name: 'APIs REST',
              description: 'Versionamento, autenticacao e documentacao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bpy-db',
              name: 'Banco Relacional',
              description: 'SQL, ORM, migrations e performance.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bpy-ops',
              name: 'Deploy e Observabilidade',
              description: 'Logs, metricas, Docker e CI/CD.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bpy-foundations',
              title: 'Fundamentos Python',
              summary: 'Base solida, typing e testes.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-fastapi',
              title: 'APIs com FastAPI',
              summary: 'Rotas, validacao, auth e documentacao.',
              estimatedHours: 20,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-postgres',
              title: 'Persistencia com Postgres',
              summary: 'Modelagem, migrations e queries.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-background',
              title: 'Background Jobs e Deploy',
              summary: 'Filas, Docker, logging e deploy.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-php',
          name: 'Backend PHP',
          description:
              'Laravel moderno, APIs, filas, testes e aplicacoes de negocio.',
          iconKey: 'code',
          colorHex: '#FFC857',
          roadmapSummary:
              'PHP moderno, Laravel, arquitetura em camadas, filas e deploy.',
          skills: [
            SkillSeed(
              id: 'skill-bphp-php',
              name: 'PHP Moderno',
              description: 'POO, Composer, tipagem e boas praticas.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bphp-laravel',
              name: 'Laravel',
              description: 'Eloquent, jobs, events e auth.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bphp-sql',
              name: 'MySQL e Postgres',
              description: 'Queries, indices e tuning.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bphp-tests',
              name: 'Testes',
              description: 'Feature tests, unit tests e contratos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bphp-core',
              title: 'Core PHP',
              summary: 'Base solida com Composer e POO.',
              estimatedHours: 12,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-laravel-api',
              title: 'Laravel API',
              summary: 'Controllers, resources, auth e filas.',
              estimatedHours: 22,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-data',
              title: 'Persistencia e Cache',
              summary: 'Migrations, cache e performance.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-ops',
              title: 'Deploy e Observabilidade',
              summary: 'CI/CD, Horizon, logs e monitoramento.',
              estimatedHours: 14,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-frontend-react',
          name: 'Front-end React',
          description:
              'Interfaces modernas, performance, componentizacao e testes.',
          iconKey: 'monitor',
          colorHex: '#35D39A',
          roadmapSummary:
              'HTML, CSS, JavaScript, React, estado, design system e deploy front.',
          skills: [
            SkillSeed(
              id: 'skill-fr-react',
              name: 'React',
              description: 'Hooks, arquitetura e roteamento.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-fr-typescript',
              name: 'TypeScript',
              description: 'Tipos, inferencia e modelagem.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-fr-ui',
              name: 'UI Engineering',
              description: 'Layout responsivo, acessibilidade e motion.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-fr-tests',
              name: 'Testes Front-end',
              description: 'Unitarios, integracao e e2e.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-fr-js-ts',
              title: 'JavaScript e TypeScript',
              summary: 'Base de linguagem para aplicacoes ricas.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-react',
              title: 'React Profissional',
              summary: 'Hooks, estado e arquitetura.',
              estimatedHours: 24,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-design-system',
              title: 'Design System e UX',
              summary: 'Tokens, componentes e acessibilidade.',
              estimatedHours: 14,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-testing',
              title: 'Qualidade Front-end',
              summary: 'Testes, performance e monitoramento.',
              estimatedHours: 12,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-full-stack',
          name: 'Full Stack',
          description: 'Fluxo ponta a ponta com front, back, banco e deploy.',
          iconKey: 'layers',
          colorHex: '#7B61FF',
          roadmapSummary:
              'Base web, API, banco, autenticacao, deploy e produto completo.',
          skills: [
            SkillSeed(
              id: 'skill-fs-front',
              name: 'Front-end',
              description: 'React, UI e consumo de APIs.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-fs-back',
              name: 'Back-end',
              description: 'APIs, auth e regras de negocio.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-fs-db',
              name: 'Banco de Dados',
              description: 'Modelagem e queries eficientes.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-fs-product',
              name: 'Entrega de Produto',
              description: 'Deploy, feedback e evolucao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-fs-web',
              title: 'Fundamentos Web',
              summary: 'HTTP, HTML, CSS e JavaScript.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-app',
              title: 'Aplicacao Completa',
              summary: 'Front-end, back-end e auth.',
              estimatedHours: 26,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-db',
              title: 'Persistencia e Deploy',
              summary: 'Banco, Docker e publicacao.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-scale',
              title: 'Escala e Observabilidade',
              summary: 'Logs, metricas e iteracao.',
              estimatedHours: 12,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-devops',
          name: 'DevOps',
          description:
              'Automacao, infraestrutura, containers, pipelines e observabilidade.',
          iconKey: 'cloud',
          colorHex: '#118AB2',
          roadmapSummary: 'Linux, redes, Docker, CI/CD, cloud e monitoramento.',
          skills: [
            SkillSeed(
              id: 'skill-do-linux',
              name: 'Linux e Shell',
              description: 'Base operacional e automacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-do-docker',
              name: 'Containers',
              description: 'Docker, registries e imagens.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-do-cicd',
              name: 'CI/CD',
              description: 'Pipelines, quality gates e deploy.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-do-observability',
              name: 'Observabilidade',
              description: 'Logs, metricas, tracing e alertas.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-do-linux',
              title: 'Linux e Redes',
              summary: 'Base operacional para ambiente real.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-docker',
              title: 'Docker e Containers',
              summary: 'Imagens, compose e boas praticas.',
              estimatedHours: 18,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-cicd',
              title: 'Pipelines CI/CD',
              summary: 'Automacao de build, testes e deploy.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-cloud',
              title: 'Cloud e Observabilidade',
              summary: 'Infra basica, monitoramento e custos.',
              estimatedHours: 20,
              sortOrder: 4,
              isCore: true,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-bi-analyst',
          name: 'BI / Data Analyst',
          description:
              'Analise, metricas, visualizacao, storytelling e produto.',
          iconKey: 'chart',
          colorHex: '#FFB703',
          roadmapSummary:
              'SQL, metricas, dashboards, estatistica aplicada e storytelling.',
          skills: [
            SkillSeed(
              id: 'skill-bi-sql',
              name: 'SQL',
              description: 'Consultas, janelas e limpeza de dados.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bi-metrics',
              name: 'Metricas',
              description: 'KPIs, funis e analise de negocio.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bi-viz',
              name: 'Visualizacao',
              description: 'Dashboards claros e tomada de decisao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bi-storytelling',
              name: 'Storytelling',
              description: 'Comunicacao executiva e insight acionavel.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bi-sql',
              title: 'SQL para Analytics',
              summary: 'Transformacoes, KPIs e camadas semanticas.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-metrics',
              title: 'Metricas de Produto e Negocio',
              summary: 'Definicao, interpretacao e analise.',
              estimatedHours: 14,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-dashboard',
              title: 'Dashboards Executivos',
              summary: 'Visualizacao, narrativa e decisoes.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-case',
              title: 'Case Analitico',
              summary: 'Projeto fim a fim orientado a negocio.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-java',
          name: 'Backend Java',
          description:
              'APIs enterprise com Java, Spring, mensageria, testes e observabilidade.',
          iconKey: 'server',
          colorHex: '#E76F51',
          roadmapSummary:
              'Java moderno, Spring Boot, persistencia, filas, seguranca e escala.',
          skills: [
            SkillSeed(
              id: 'skill-bj-java',
              name: 'Java Moderno',
              description: 'Colecoes, streams, concorrencia e clean code.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bj-spring',
              name: 'Spring Boot',
              description: 'REST, seguranca, configuracao e arquitetura.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bj-data',
              name: 'Persistencia',
              description: 'JPA, SQL, migrations e performance.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bj-ops',
              name: 'Mensageria e Observabilidade',
              description: 'Kafka, logs, metricas e tracing.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bj-java-core',
              title: 'Java Core',
              summary: 'Base moderna de linguagem, testes e padroes.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bj-spring',
              title: 'APIs com Spring Boot',
              summary: 'Controllers, services, auth e documentacao.',
              estimatedHours: 24,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bj-persistence',
              title: 'Persistencia e Integracoes',
              summary: 'JPA, SQL, cache e integracoes externas.',
              estimatedHours: 20,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bj-messaging',
              title: 'Mensageria e Escala',
              summary: 'Filas, eventos, resiliencia e observabilidade.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-dotnet',
          name: 'Backend .NET',
          description:
              'APIs com C#, ASP.NET Core, arquitetura limpa, testes e cloud.',
          iconKey: 'code',
          colorHex: '#5A189A',
          roadmapSummary:
              'C#, ASP.NET Core, Entity Framework, filas, cloud e monitoramento.',
          skills: [
            SkillSeed(
              id: 'skill-bdn-csharp',
              name: 'C#',
              description: 'Sintaxe moderna, LINQ, async e boas praticas.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bdn-aspnet',
              name: 'ASP.NET Core',
              description: 'REST, autenticacao, middlewares e versionamento.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bdn-data',
              name: 'Dados',
              description: 'EF Core, SQL, migrations e tuning.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bdn-cloud',
              name: 'Entrega e Cloud',
              description: 'Docker, Azure, logs e telemetria.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bdn-csharp',
              title: 'Fundamentos C#',
              summary: 'Base solida de linguagem, testes e async.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bdn-aspnet',
              title: 'APIs com ASP.NET Core',
              summary: 'Controllers, identity, middlewares e contratos.',
              estimatedHours: 22,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bdn-data',
              title: 'Persistencia com EF Core',
              summary: 'Relacionamentos, consultas e migrations.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bdn-cloud',
              title: 'Deploy, Mensageria e Monitoramento',
              summary: 'Containers, filas, Azure e observabilidade.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-mobile-flutter',
          name: 'Mobile Flutter',
          description:
              'Apps multiplataforma com Flutter, UX nativa, estado e publicacao.',
          iconKey: 'monitor',
          colorHex: '#00B4D8',
          roadmapSummary:
              'Dart, Flutter, estado, integracao com APIs, offline first e release.',
          skills: [
            SkillSeed(
              id: 'skill-mf-dart',
              name: 'Dart',
              description: 'Sintaxe, orientacao a objetos, async e colecoes.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-mf-ui',
              name: 'Flutter UI',
              description: 'Widgets, layout responsivo e acessibilidade.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-mf-state',
              name: 'Gerencia de Estado',
              description: 'Riverpod, arquitetura e ciclo de vida.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-mf-release',
              name: 'Entrega Mobile',
              description: 'Builds, analytics, crash reports e stores.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-mf-dart',
              title: 'Fundamentos Dart',
              summary: 'Base de linguagem e padroes usados no Flutter.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-mf-flutter',
              title: 'Flutter Profissional',
              summary: 'Widgets, navegacao, temas e experiencia nativa.',
              estimatedHours: 24,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-mf-state',
              title: 'Arquitetura e Estado',
              summary: 'Riverpod, testes, offline first e repositorios.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-mf-release',
              title: 'Integracoes e Release',
              summary: 'APIs, autenticacao, analytics e publicacao.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-qa-automation',
          name: 'QA Automation',
          description:
              'Qualidade de software com estrategia, automacao, performance e CI.',
          iconKey: 'book',
          colorHex: '#90BE6D',
          roadmapSummary:
              'Teste manual, automacao web e API, qualidade continua e observabilidade.',
          skills: [
            SkillSeed(
              id: 'skill-qa-strategy',
              name: 'Estrategia de Qualidade',
              description: 'Piramide de testes, riscos e criterios de aceite.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-qa-api',
              name: 'Testes de API',
              description: 'Contratos, colecoes, mocks e automacao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-qa-ui',
              name: 'Automacao UI',
              description: 'Playwright, Cypress e estabilidade de suite.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-qa-performance',
              name: 'Performance e Qualidade Continua',
              description: 'Carga, rastreabilidade e pipelines.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-qa-foundations',
              title: 'Fundamentos de QA',
              summary: 'Processo, bugs, cobertura e qualidade por risco.',
              estimatedHours: 12,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-qa-api',
              title: 'Automacao de APIs',
              summary: 'REST, contratos, dados de teste e suites.',
              estimatedHours: 18,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-qa-ui',
              title: 'Automacao End-to-End',
              summary: 'Playwright, seletores, fixtures e paralelismo.',
              estimatedHours: 20,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-qa-performance',
              title: 'Performance e CI',
              summary: 'Testes de carga, relatorios e gates de release.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-cybersecurity',
          name: 'Cybersecurity',
          description:
              'Seguranca ofensiva e defensiva, AppSec, IAM, monitoramento e resposta.',
          iconKey: 'layers',
          colorHex: '#EF476F',
          roadmapSummary:
              'Redes, vulnerabilidades, hardening, identidade, SIEM e incident response.',
          skills: [
            SkillSeed(
              id: 'skill-cs-network',
              name: 'Fundamentos de Rede',
              description: 'TCP/IP, DNS, HTTP e superficies de ataque.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-cs-appsec',
              name: 'AppSec',
              description: 'OWASP, autenticacao, secrets e seguranca em SDLC.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-cs-iam',
              name: 'IAM e Hardening',
              description:
                  'Acesso minimo, MFA, politicas e configuracao segura.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-cs-detection',
              name: 'Deteccao e Resposta',
              description: 'Logs, alertas, SIEM e investigacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-cs-network',
              title: 'Redes e Ameacas',
              summary: 'Protocolos, arquitetura e vetores de ataque.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cs-appsec',
              title: 'Seguranca de Aplicacoes',
              summary: 'OWASP Top 10, SDLC seguro e revisao tecnica.',
              estimatedHours: 20,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cs-iam',
              title: 'IAM e Hardening',
              summary:
                  'Controles de acesso, secrets, backup e baseline segura.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cs-detection',
              title: 'Monitoramento e Resposta',
              summary: 'SIEM, playbooks e tratamento de incidentes.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-cloud-platform',
          name: 'Cloud Platform',
          description:
              'Infraestrutura moderna com cloud, IaC, Kubernetes, redes e custo.',
          iconKey: 'cloud',
          colorHex: '#4EA8DE',
          roadmapSummary:
              'AWS, Azure ou GCP, redes, Terraform, containers e operacao de plataforma.',
          skills: [
            SkillSeed(
              id: 'skill-cp-cloud',
              name: 'Cloud Core',
              description:
                  'Compute, storage, redes, IAM e servicos gerenciados.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-cp-terraform',
              name: 'Infra as Code',
              description: 'Terraform, modulos, estado e automacao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-cp-k8s',
              name: 'Kubernetes',
              description: 'Deployments, services, ingress e operacao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-cp-finops',
              name: 'FinOps e Governanca',
              description: 'Custos, tagging, quotas e padroes.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-cp-cloud',
              title: 'Fundamentos de Cloud',
              summary: 'Construa base de arquitetura e seguranca em cloud.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cp-terraform',
              title: 'Terraform na Pratica',
              summary: 'Provisionamento, reuso, pipelines e padroes.',
              estimatedHours: 18,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cp-k8s',
              title: 'Kubernetes Operacional',
              summary: 'Workloads, observabilidade, segredo e rollout.',
              estimatedHours: 22,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-cp-governance',
              title: 'Governanca e Custos',
              summary: 'FinOps, compliance, rede e plataforma compartilhada.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-data-science-ml',
          name: 'Data Science / ML',
          description:
              'Modelagem estatistica, machine learning, experimentos e deploy de modelos.',
          iconKey: 'chart',
          colorHex: '#8338EC',
          roadmapSummary:
              'Python, estatistica, feature engineering, treinamento, avaliacao e MLOps.',
          skills: [
            SkillSeed(
              id: 'skill-ds-python',
              name: 'Python para Ciencia de Dados',
              description: 'Numpy, pandas, notebooks e reproducao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-ds-stats',
              name: 'Estatistica Aplicada',
              description: 'Probabilidade, inferencia, testes e experimentos.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-ds-ml',
              name: 'Machine Learning',
              description: 'Modelos supervisionados, validacao e tuning.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-ds-mle',
              name: 'MLOps',
              description: 'Deploy, monitoramento, drift e ciclo de modelos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-ds-python',
              title: 'Python e Analise Exploratoria',
              summary: 'Limpeza, visualizacao e reproducao de dados.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ds-stats',
              title: 'Estatistica para Produto',
              summary: 'Hipoteses, testes, metricas e variabilidade.',
              estimatedHours: 16,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ds-ml',
              title: 'Modelagem de ML',
              summary: 'Treino, avaliacao, features e interpretacao.',
              estimatedHours: 22,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ds-mlops',
              title: 'MLOps e Producao',
              summary: 'Servir modelos, monitorar e iterar com seguranca.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-ai-engineering',
          name: 'AI Engineering',
          description:
              'Aplicacoes com LLM, RAG, avaliacoes, agentes e operacao em producao.',
          iconKey: 'rocket',
          colorHex: '#F3722C',
          roadmapSummary:
              'LLMs, prompt engineering, RAG, evals, safety, custo e integracao com produto.',
          skills: [
            SkillSeed(
              id: 'skill-ai-llm',
              name: 'LLM Apps',
              description: 'Prompts, ferramentas, cadeias e UX conversacional.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-ai-rag',
              name: 'RAG e Busca',
              description: 'Embeddings, chunking, retrieval e grounding.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-ai-evals',
              name: 'Avaliacao',
              description:
                  'Metrica, datasets, regressao e criterios de qualidade.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-ai-ops',
              name: 'AI Ops',
              description: 'Custos, observabilidade, seguranca e operacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-ai-llm',
              title: 'Fundamentos de LLM',
              summary: 'Capacidades, limites, prompting e design de fluxo.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ai-rag',
              title: 'RAG em Producao',
              summary: 'Indexacao, retrieval, citacoes e atualizacao de base.',
              estimatedHours: 20,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ai-evals',
              title: 'Evals e Qualidade',
              summary: 'Benchmarks, avaliacao automatica e revisao humana.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ai-ops',
              title: 'Operacao de AI',
              summary: 'Seguranca, custo, rate limits e governanca.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-database-admin',
          name: 'Database Administrator',
          description:
              'Administracao de bancos, backup, replicacao, tuning e alta disponibilidade.',
          iconKey: 'database',
          colorHex: '#3A86FF',
          roadmapSummary:
              'SQL, operacao, performance, seguranca, backup e recuperacao.',
          skills: [
            SkillSeed(
              id: 'skill-dba-sql',
              name: 'SQL e Modelagem',
              description: 'Esquema, integridade, indexes e consulta.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-dba-admin',
              name: 'Administracao',
              description: 'Usuarios, permissao, jobs e manutencao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-dba-tuning',
              name: 'Performance',
              description: 'Planos de execucao, cache e tuning.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-dba-recovery',
              name: 'Backup e Recuperacao',
              description: 'Rotinas, replicacao e DR.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-dba-sql',
              title: 'Base de Dados Relacionais',
              summary: 'Modelagem, constraints e consistencia.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-dba-admin',
              title: 'Operacao de Banco',
              summary: 'Roles, jobs, manutencao e automacao.',
              estimatedHours: 16,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-dba-tuning',
              title: 'Tuning e Diagnostico',
              summary: 'Analise de queries, indices e gargalos.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-dba-recovery',
              title: 'Backup, Replicacao e DR',
              summary: 'Alta disponibilidade e recuperacao segura.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-network-infra',
          name: 'Network & Infrastructure',
          description:
              'Redes corporativas, roteamento, firewall, servicos e infraestrutura base.',
          iconKey: 'server',
          colorHex: '#577590',
          roadmapSummary:
              'TCP/IP, switching, routing, VPN, DNS, servicos e troubleshooting.',
          skills: [
            SkillSeed(
              id: 'skill-ni-networking',
              name: 'Fundamentos de Rede',
              description: 'Modelo OSI, IP, sub-redes e protocolos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-ni-routing',
              name: 'Routing e Switching',
              description: 'VLAN, roteamento, redundancia e segmentacao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-ni-security',
              name: 'Firewall e Acesso',
              description: 'ACLs, VPN, NAT e politicas.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-ni-services',
              name: 'Servicos de Infra',
              description: 'DNS, DHCP, proxy e monitoramento.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-ni-network',
              title: 'Redes na Pratica',
              summary: 'Enderecamento, troubleshooting e topologias.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ni-routing',
              title: 'Routing e Switching',
              summary: 'VLAN, STP, OSPF e boas praticas.',
              estimatedHours: 20,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ni-security',
              title: 'Seguranca Perimetral',
              summary: 'Firewall, VPN e segmentacao segura.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ni-services',
              title: 'Servicos e Operacao',
              summary: 'DNS, DHCP, NTP, proxy e observabilidade.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-linux-systems',
          name: 'Linux & Systems',
          description:
              'Administracao Linux, automacao, processos, servicos e troubleshooting.',
          iconKey: 'cloud',
          colorHex: '#06D6A0',
          roadmapSummary:
              'Shell, usuarios, servicos, automacao, logs, backups e diagnostico.',
          skills: [
            SkillSeed(
              id: 'skill-ls-linux',
              name: 'Linux Core',
              description: 'Filesystem, usuarios, permissoes e processos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-ls-shell',
              name: 'Shell Scripting',
              description: 'Bash, pipes, scripts e automacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-ls-automation',
              name: 'Automacao de Sistema',
              description: 'Cron, services, provisionamento e configuracao.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-ls-monitoring',
              name: 'Monitoramento e Troubleshooting',
              description: 'Logs, recursos, rede e incidentes.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-ls-linux',
              title: 'Administracao Linux',
              summary: 'Base operacional para servidores e estacoes.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ls-shell',
              title: 'Shell e Automacao',
              summary: 'Scripts reutilizaveis e produtividade operacional.',
              estimatedHours: 14,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ls-services',
              title: 'Servicos e Provisionamento',
              summary: 'Systemd, tarefas e padroes de configuracao.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ls-troubleshooting',
              title: 'Diagnostico e Monitoramento',
              summary: 'Analise de logs, recursos e falhas.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-ui-ux',
          name: 'UI / UX Design',
          description:
              'Pesquisa, arquitetura de informacao, interfaces, design system e prototipacao.',
          iconKey: 'monitor',
          colorHex: '#FF6B6B',
          roadmapSummary:
              'Pesquisa com usuario, fluxos, componentes, handoff e medicao de experiencia.',
          skills: [
            SkillSeed(
              id: 'skill-ux-research',
              name: 'Research',
              description: 'Entrevistas, sintese, personas e descoberta.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-ux-ia',
              name: 'Arquitetura de Informacao',
              description: 'Fluxos, hierarquia e navegacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-ux-design-system',
              name: 'Design System',
              description:
                  'Tokens, componentes, acessibilidade e consistencia.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-ux-prototype',
              name: 'Prototipacao e Handoff',
              description: 'Figma, prototipos, testes e especificacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-ux-research',
              title: 'Pesquisa e Descoberta',
              summary: 'Base para entender usuarios, tarefas e contexto.',
              estimatedHours: 12,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ux-ia',
              title: 'Fluxos e Arquitetura',
              summary: 'Estruture experiencias claras e navegaveis.',
              estimatedHours: 14,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ux-system',
              title: 'Design System',
              summary: 'Construa componentes, tokens e linguagem visual.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-ux-prototype',
              title: 'Prototipos e Validacao',
              summary: 'Teste hipoteses, documente e acompanhe entrega.',
              estimatedHours: 14,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-it-support',
          name: 'IT Support',
          description:
              'Suporte tecnico, diagnostico, endpoint management, redes e atendimento.',
          iconKey: 'book',
          colorHex: '#6C757D',
          roadmapSummary:
              'Hardware, sistemas operacionais, redes, tickets, inventario e padroes de atendimento.',
          skills: [
            SkillSeed(
              id: 'skill-its-operating',
              name: 'Sistemas Operacionais',
              description: 'Windows, Linux, instalacao e configuracao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-its-network',
              name: 'Redes e Acesso',
              description: 'Wi-Fi, VPN, DNS e diagnostico basico.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-its-ticketing',
              name: 'Processo de Suporte',
              description: 'Tickets, SLA, documentacao e comunicacao.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-its-endpoint',
              name: 'Endpoints e Inventario',
              description: 'Dispositivos, politicas e ciclo de vida.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-its-os',
              title: 'Base de Suporte Tecnico',
              summary: 'SO, instalacoes, configuracao e atendimento.',
              estimatedHours: 12,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-its-network',
              title: 'Diagnostico de Rede',
              summary: 'Conectividade, VPN, impressao e acesso.',
              estimatedHours: 12,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-its-process',
              title: 'Operacao de Service Desk',
              summary: 'Tickets, runbooks, SLA e base de conhecimento.',
              estimatedHours: 14,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-its-endpoint',
              title: 'Gestao de Equipamentos',
              summary: 'Inventario, seguranca, atualizacao e padronizacao.',
              estimatedHours: 14,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
      ],
    );
  }
}
